/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLNhanVien;

import Main.Main2;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xiaomi
 */
public class HoSoNhanSu extends javax.swing.JFrame {

    /**
     * Creates new form HoSoNhanSu
     */
    public static ResultSet rs=null;
    public Statement st;
    Connect cn=new Connect();
   
     private void LoadData()
    {
        cn.getConnect();
        try {
            rs=cn.GetDataNV("NHANVIEN");
            NVjTableNhanVien.removeAll();
            String []tieuDe={"Mã Nhân Viên","Họ Tên","Ngày Sinh","Giới Tính","Trình Độ","Số Điện Thoại","Địa Chỉ","Mã Khoa"};
            DefaultTableModel model=new DefaultTableModel(tieuDe,0);
            while(rs.next())
            {
                Vector vt=new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                vt.add(rs.getString(5));
                vt.add(rs.getString(6));
                vt.add(rs.getString(7));
                vt.add(rs.getString(8));
                model.addRow(vt);
            }
            NVjTableNhanVien.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      public HoSoNhanSu() {
        initComponents();
        LoadData();
        ButtonGroup bd = new ButtonGroup();
        bd.add(NVrdNu);
        bd.add(NVrdNam);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        NVbtnTimKiem = new javax.swing.JButton();
        NVbtnDanhSach = new javax.swing.JButton();
        jComboTimKiem = new javax.swing.JComboBox<>();
        rdNu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NVtxtMaNhanVien = new javax.swing.JTextField();
        NVtxtHoTenNhanVien = new javax.swing.JTextField();
        NVtxtNgaySinh = new javax.swing.JTextField();
        NVrdNam = new javax.swing.JRadioButton();
        NVrdNu = new javax.swing.JRadioButton();
        NVtxtMaKhoa = new javax.swing.JTextField();
        NVtxtTrinhDo = new javax.swing.JTextField();
        NVtxtSdt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        NVtxtDiaChi = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NVjTableNhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        NVbtnThem = new javax.swing.JButton();
        NVbtnSua = new javax.swing.JButton();
        NVbtnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        NVbtnQuayLai = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tìm theo:");

        NVbtnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NVbtnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Util/Icon/Search.png"))); // NOI18N
        NVbtnTimKiem.setText("Tìm Kiếm");
        NVbtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVbtnTimKiemActionPerformed(evt);
            }
        });

        NVbtnDanhSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NVbtnDanhSach.setText("Danh sách nhân viên");
        NVbtnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVbtnDanhSachActionPerformed(evt);
            }
        });

        jComboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã nhân viên", "Tên nhân viên", " " }));
        jComboTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NVbtnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(166, 166, 166)
                .addComponent(NVbtnDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NVbtnDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NVbtnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(jComboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        rdNu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã Nhân Viên:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Họ Tên Nhân Viên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ngày Sinh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Giới Tính:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mã Khoa:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Trình Độ:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Số Điện Thoại:");

        NVtxtMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NVtxtHoTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NVtxtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NVrdNam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NVrdNam.setText("Nam");

        NVrdNu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NVrdNu.setText("Nữ");

        NVtxtMaKhoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NVtxtTrinhDo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NVtxtSdt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Địa Chỉ:");

        javax.swing.GroupLayout rdNuLayout = new javax.swing.GroupLayout(rdNu);
        rdNu.setLayout(rdNuLayout);
        rdNuLayout.setHorizontalGroup(
            rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdNuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rdNuLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(NVrdNam)
                        .addGap(18, 18, 18)
                        .addComponent(NVrdNu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rdNuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NVtxtMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NVtxtHoTenNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NVtxtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NVtxtMaKhoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NVtxtTrinhDo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NVtxtSdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NVtxtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        rdNuLayout.setVerticalGroup(
            rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdNuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NVtxtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NVtxtHoTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NVtxtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NVrdNam)
                    .addComponent(NVrdNu))
                .addGap(30, 30, 30)
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NVtxtTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NVtxtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(41, 41, 41)
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NVtxtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(30, 30, 30)
                .addGroup(rdNuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NVtxtMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(950, 485));

        NVjTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        NVjTableNhanVien.setPreferredSize(new java.awt.Dimension(300, 600));
        NVjTableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NVjTableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(NVjTableNhanVien);
        if (NVjTableNhanVien.getColumnModel().getColumnCount() > 0) {
            NVjTableNhanVien.getColumnModel().getColumn(1).setMinWidth(150);
        }

        jPanel3.setLayout(new java.awt.GridLayout(1, 5));

        NVbtnThem.setBackground(new java.awt.Color(255, 255, 255));
        NVbtnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NVbtnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Util/Icon/Add.png"))); // NOI18N
        NVbtnThem.setText("Thêm Mới");
        NVbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVbtnThemActionPerformed(evt);
            }
        });
        jPanel3.add(NVbtnThem);

        NVbtnSua.setBackground(new java.awt.Color(255, 255, 255));
        NVbtnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NVbtnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Util/Icon/Edit.png"))); // NOI18N
        NVbtnSua.setText("Sửa");
        NVbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVbtnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(NVbtnSua);

        NVbtnXoa.setBackground(new java.awt.Color(255, 255, 255));
        NVbtnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NVbtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Util/Icon/Delete.png"))); // NOI18N
        NVbtnXoa.setText("Xóa");
        NVbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVbtnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(NVbtnXoa);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Util/Icon/Refresh.png"))); // NOI18N
        jButton1.setText("Sắp xếp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        NVbtnQuayLai.setBackground(new java.awt.Color(255, 255, 255));
        NVbtnQuayLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NVbtnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Util/Icon/Exit.png"))); // NOI18N
        NVbtnQuayLai.setText("Quay Lại");
        NVbtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVbtnQuayLaiActionPerformed(evt);
            }
        });
        jPanel3.add(NVbtnQuayLai);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rdNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NVbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVbtnThemActionPerformed
        // TODO add your handling code here:
        cn.getConnect();
        try {
            if(!checksize())JOptionPane.showMessageDialog(this, "Phải nhập thông tin đầy đủ","", JOptionPane.ERROR_MESSAGE);
            else if(cn.checkStudent(NVtxtMaNhanVien.getText()))JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại","", JOptionPane.ERROR_MESSAGE);
            else if(!Pattern.matches("[N][V][0-9 ]{3,}", NVtxtMaNhanVien.getText()))JOptionPane.showMessageDialog(this, "Mã nhân viên không đúng định dạng", "", JOptionPane.ERROR_MESSAGE);
            else if(!Pattern.matches("^\\d{4}[-|/]\\d{2}[-|/]\\d{2}$", NVtxtNgaySinh.getText()))JOptionPane.showMessageDialog(this,"Ngày sinh không đúng định dạng" ," ", JOptionPane.ERROR_MESSAGE);
            else if(cn.checkSdt(NVtxtSdt.getText()))JOptionPane.showMessageDialog(this, "Số điện thoại không được trùng","", JOptionPane.ERROR_MESSAGE);
            else if(!cn.checkKhoa(NVtxtMaKhoa.getText()))JOptionPane.showMessageDialog(this, "Mã khoa không tồn tại","", JOptionPane.ERROR_MESSAGE);
            else{
            cn.addNV(NVtxtMaNhanVien.getText(),NVtxtHoTenNhanVien.getText(),NVtxtNgaySinh.getText(),getGT(),NVtxtTrinhDo.getText(), NVtxtSdt.getText(), NVtxtDiaChi.getText(), NVtxtMaKhoa.getText()) ;
            xoatrangNV();
            }
            } catch (Exception ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadData();
        try {
            cn.closeConnect();
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_NVbtnThemActionPerformed
    private boolean checksize(){
        if(NVtxtMaNhanVien.getText().isEmpty())
            return false;
        if(NVtxtHoTenNhanVien.getText().isEmpty())
            return  false;
        if(NVtxtNgaySinh.getText().isEmpty())
            return  false;
        if(NVtxtTrinhDo.getText().isEmpty())
            return  false;
        if(NVtxtSdt.getText().isEmpty())
            return  false;
        if(NVtxtDiaChi.getText().isEmpty())
            return  false;
        if(NVtxtMaKhoa.getText().isEmpty())
            return  false;
        return true;
    }
    private void NVjTableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVjTableNhanVienMouseClicked
        // TODO add your handling code here:
        int vitri;
        vitri=evt.getClickCount();
        if(vitri>=0)
        {
            NVtxtMaNhanVien.setText(NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 0).toString());
            NVtxtHoTenNhanVien.setText(NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 1).toString());
            NVtxtNgaySinh.setText(NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 2).toString());
            if((NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 3).toString()).equals("Nam")){
                NVrdNam.setSelected(true);
            }
            else{
                NVrdNu.setSelected(true);
            }
            NVtxtTrinhDo.setText(NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 4).toString());
            NVtxtSdt.setText(NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 5).toString());
            NVtxtDiaChi.setText(NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 6).toString());
            NVtxtMaKhoa.setText(NVjTableNhanVien.getValueAt(NVjTableNhanVien.getSelectedRow(), 7).toString());
        }
    }//GEN-LAST:event_NVjTableNhanVienMouseClicked

    private void NVbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVbtnXoaActionPerformed
        // TODO add your handling code here:
        cn.getConnect();
        try {
            if(NVtxtMaNhanVien.getText().isEmpty()){
                JOptionPane.showConfirmDialog(this, "Chưa chọn mã nhân viên cần xóa","",JOptionPane.ERROR_MESSAGE);
            }
            else if(!cn.checkStudent(NVtxtMaNhanVien.getText()))JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên cần xóa","", JOptionPane.ERROR_MESSAGE);
            else{
            cn.removeNV(NVtxtMaNhanVien.getText());
            cn.removeLuong(NVtxtMaNhanVien.getText());
            }
        } catch (Exception ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadData();
        try {
            cn.closeConnect();
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cn.closeConnect();
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadData();
        xoatrangNV();
    }//GEN-LAST:event_NVbtnXoaActionPerformed

    private void NVbtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVbtnQuayLaiActionPerformed
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        new Main2().setVisible(true);
    }//GEN-LAST:event_NVbtnQuayLaiActionPerformed

    private void NVbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVbtnSuaActionPerformed
        // TODO add your handling code here:
        cn.getConnect();
        try {
            if(!checksize())JOptionPane.showMessageDialog(this, "Phải nhập thông tin đầy đủ","", JOptionPane.ERROR_MESSAGE);
            else if(!Pattern.matches("[N][V][0-9 ]{3,}", NVtxtMaNhanVien.getText()))JOptionPane.showMessageDialog(this, "Mã nhân viên không đúng định dạng", "", JOptionPane.ERROR_MESSAGE);
            else if(!Pattern.matches("^\\d{4}[-|/]\\d{2}[-|/]\\d{2}$", NVtxtNgaySinh.getText()))JOptionPane.showMessageDialog(this,"Ngày sinh không đúng định dạng" ," ", JOptionPane.ERROR_MESSAGE);
            else if(!cn.checkKhoa(NVtxtMaKhoa.getText()))JOptionPane.showMessageDialog(this, "Mã khoa không tồn tại","", JOptionPane.ERROR_MESSAGE);
            else{
            cn.updateNV(NVtxtMaNhanVien.getText(),NVtxtHoTenNhanVien.getText(),NVtxtNgaySinh.getText(),getGT(),NVtxtTrinhDo.getText(), NVtxtSdt.getText(), NVtxtDiaChi.getText(), NVtxtMaKhoa.getText()) ;
            xoatrangNV();
            }
        } catch (Exception ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadData();
        try {
            cn.closeConnect();
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cn.closeConnect();
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cn.closeConnect();
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
    }//GEN-LAST:event_NVbtnSuaActionPerformed

    private void NVbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVbtnTimKiemActionPerformed

        switch (jComboTimKiem.getSelectedIndex()) {
            case 0:
            {
                try {
                    timKiemTheoMa();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;
            case 1:
            {
                try {
                    timKiemTheoTen();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;
        }
    }//GEN-LAST:event_NVbtnTimKiemActionPerformed

    private void NVbtnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVbtnDanhSachActionPerformed
        // TODO add your handling code here:        
        LoadData();
    }//GEN-LAST:event_NVbtnDanhSachActionPerformed

    private void jComboTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTimKiemActionPerformed

    }//GEN-LAST:event_jComboTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cn.getConnect();
        try {
            rs=cn.sort("NHANVIEN");
            NVjTableNhanVien.removeAll();
            String []tieuDe={"Mã Nhân Viên","Họ Tên","Ngày Sinh","Giới Tính","Trình Độ","Số Điện Thoại","Địa Chỉ","Mã Khoa"};
            DefaultTableModel model=new DefaultTableModel(tieuDe,0);
            while(rs.next())
            {
                Vector vt=new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                vt.add(rs.getString(5));
                vt.add(rs.getString(6));
                vt.add(rs.getString(7));
                vt.add(rs.getString(8));
                model.addRow(vt);
            }
            NVjTableNhanVien.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public String getGT(){
        if(NVrdNu.isSelected()) return "Nữ";
        return "Nam";
    }
    public void xoatrangNV(){
        NVtxtMaNhanVien.setText("");
        NVtxtHoTenNhanVien.setText("");
        NVtxtNgaySinh.setText("");
        NVtxtTrinhDo.setText("");
        NVtxtSdt.setText("");
        NVtxtDiaChi.setText("");
        NVtxtMaKhoa.setText("");
    }
    private void timKiemTheoMa() throws ClassNotFoundException
    {
        cn.getConnect();
        try {
            JPanel f = new JPanel(new GridLayout(4, 1));
            f.add(new JLabel("Nhập Mã nhân viên: "));
            JTextField maNV = new JTextField(10);
            f.add(maNV);
            int result= JOptionPane.showConfirmDialog(null, f, " ",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(result==0){
            if(maNV.getText().isEmpty())JOptionPane.showMessageDialog(this, "Chưa nhập mã nhân viên cần tìm","", JOptionPane.ERROR_MESSAGE);
            else if(!cn.checkStudent(maNV.getText()))JOptionPane.showMessageDialog(this, "Mã nhân viên không tồn tại","", JOptionPane.ERROR_MESSAGE);
            else{
            rs=cn.findNVBySid(maNV.getText());
            NVjTableNhanVien.removeAll();
            String []tieuDe={"Mã Nhân Viên","Họ Tên","Ngày Sinh","Giới Tính","Trình Độ","Số Điện Thoại","Địa Chỉ","Mã Khoa"};
            DefaultTableModel model=new DefaultTableModel(tieuDe,0);
            while(rs.next())
            {
                Vector vt=new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                vt.add(rs.getString(5));
                vt.add(rs.getString(6));
                vt.add(rs.getString(7));
                vt.add(rs.getString(8));
                model.addRow(vt);
            }
            NVjTableNhanVien.setModel(model);
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void timKiemTheoTen() throws ClassNotFoundException
    {
        cn.getConnect();
        try {
            JPanel f2 = new JPanel(new GridLayout(4, 1));
            f2.add(new JLabel("Nhập Tên nhân viên: "));
            JTextField tenNV = new JTextField(30);
            f2.add(tenNV);
            int result2= JOptionPane.showConfirmDialog(null, f2, " ",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(result2==0){
            if(tenNV.getText().isEmpty())JOptionPane.showMessageDialog(this, "Chưa nhập tên nhân viên cần tìm","", JOptionPane.ERROR_MESSAGE);
            else if(!cn.checkName(tenNV.getText()))JOptionPane.showMessageDialog(this, "Tên nhân viên không tồn tại","", JOptionPane.ERROR_MESSAGE);
            else{
            rs=cn.findByName(tenNV.getText());
            NVjTableNhanVien.removeAll();
            String []tieuDe={"Mã Nhân Viên","Họ Tên","Ngày Sinh","Giới Tính","Trình Độ","Số Điện Thoại","Địa Chỉ","Mã Khoa"};
            DefaultTableModel model=new DefaultTableModel(tieuDe,0);
            while(rs.next())
            {
                Vector vt=new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                vt.add(rs.getString(4));
                vt.add(rs.getString(5));
                vt.add(rs.getString(6));
                vt.add(rs.getString(7));
                vt.add(rs.getString(8));
                model.addRow(vt);
            }
            NVjTableNhanVien.setModel(model);
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanSu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoSoNhanSu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NVbtnDanhSach;
    private javax.swing.JButton NVbtnQuayLai;
    private javax.swing.JButton NVbtnSua;
    private javax.swing.JButton NVbtnThem;
    private javax.swing.JButton NVbtnTimKiem;
    private javax.swing.JButton NVbtnXoa;
    private javax.swing.JTable NVjTableNhanVien;
    private javax.swing.JRadioButton NVrdNam;
    private javax.swing.JRadioButton NVrdNu;
    private javax.swing.JTextField NVtxtDiaChi;
    private javax.swing.JTextField NVtxtHoTenNhanVien;
    private javax.swing.JTextField NVtxtMaKhoa;
    private javax.swing.JTextField NVtxtMaNhanVien;
    private javax.swing.JTextField NVtxtNgaySinh;
    private javax.swing.JTextField NVtxtSdt;
    private javax.swing.JTextField NVtxtTrinhDo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel rdNu;
    // End of variables declaration//GEN-END:variables
}
