/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLLuong;

import Util.Luong;
import java.awt.GridLayout;
import java.awt.Label;
import java.io.File;
import java.io.FileWriter;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Hud
 */
public class QLLuongJFrame extends javax.swing.JFrame {
    private LinkedList<Luong> listL = new LinkedList<>();
    private int selectedRow = -1;
    private MConnect db= new MConnect();
    /**
     * Creates new form NewJFrame
     */
    public QLLuongJFrame() {
        initComponents();
        listL= db.getALLData("Select * from LUONG inner join NHANVIEN on LUONG.MaNhanVien = NHANVIEN.MaNhanVien");
        jTable1.setModel(new Table(listL));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Quản lý lương");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 268, 11, 279);
        jPanel1.add(jLabel1, gridBagConstraints);
        jLabel1.getAccessibleContext().setAccessibleName("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Nhân Viên"));
        jPanel2.setName(""); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Họ tên", "Ngày sinh", "Đơn vị", "Trình độ", "Chức danh", "Bậc", "Hệ số lương", "Thời điểm"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(2, 4));

        jButton6.setIcon(new ImageIcon("src/Util/ICon/Add.png"));
        jButton6.setText("Thêm");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton2.setIcon(new ImageIcon("src/Util/Icon/Edit.png"));
        jButton2.setText("Chỉnh sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton7.setText("Xóa");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton1.setText("Sắp xếp");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton5.setIcon(new ImageIcon("src/Util/Icon/Refresh.png"));
        jButton5.setText("Làm mới");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton3.setIcon(new ImageIcon("src/Util/Icon/Search.png"));
        jButton3.setText("Tìm kiếm ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setText("In danh sách");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton8.setText("Thoát");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel3.add(jButton8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Quản lý lương");
        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JPanel f = new JPanel(new GridLayout(4, 1));
        f.add(new Label("Tìm kiếm theo:"));
        JComboBox<String> option = new JComboBox<String>(new String[]{"Họ tên","Bậc","Trình độ"});
        f.add(option);
        f.add(new JLabel("Nhập từ khóa :"));
        JTextField tukhoa = new JTextField(30);
        f.add(tukhoa);
        int result= JOptionPane.showConfirmDialog(null, f, "Tìm kiếm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(result == 0){
            switch(option.getSelectedIndex()){
                case 0:
                    String tk =tukhoa.getText().toLowerCase();
                    for(Luong i : listL){
                        if(!i.getHotenNV().toLowerCase().contains(tk)){
                            listL.remove(i);
                        }
                    }
                    jTable1.setModel(new Table(listL));
                    break;
                case 1:
                    int tk1 = Integer.parseInt(tukhoa.getText());
                    for(Luong i : listL){
                        if(Integer.compare(i.getBac(), tk1)!=0){
                            listL.remove(i);
                        }
                    }
                    jTable1.setModel(new Table(listL));
                    break;
                case 2:
                    String tk3 =tukhoa.getText().toLowerCase();
                    for(Luong i : listL){
                        if(!i.getTrinhDo().equalsIgnoreCase(tk3)){
                            listL.remove(i);
                        }
                    }
                    jTable1.setModel(new Table(listL));
                    break;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(selectedRow == -1){
            String manv = (String) JOptionPane.showInputDialog(this, "Nhập mã nhân viên:", "Chỉnh sửa",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                "");
            if (manv != null && !manv.isEmpty()) {
                for (Luong i : listL) {
                    if (i.getMaNV().trim().equalsIgnoreCase(manv.trim())) {
                        selectedRow = listL.indexOf(i);
                        break;
                    }
                }
                if (selectedRow != -1) {
                    Edit sua = new Edit(listL.get(selectedRow), jTable1, listL, "edit");
                    sua.setVisible(rootPaneCheckingEnabled);
                    if(sua.isUpdateClick())selectedRow = -1;
                } else {
                    JOptionPane.showMessageDialog(null, "Nhân viên không tồn tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }else{
            Edit sua = new Edit(listL.get(selectedRow), jTable1, listL, "edit");
            sua.setVisible(rootPaneCheckingEnabled);
            if(sua.isUpdateClick())selectedRow = -1;
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    private String line(){
        String line="+";
        for(int i= 1; i<149; i++){
            if(i== 11 || i == 37 || i== 53 || i== 69 || i== 85 || i== 101 || i == 117 || i == 133){
                line+="+";
            }else{
                line+="-";
            }
        }
        return line+"+\n";
    }
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        File name = new File ("Danh sach.txt");
        JFileChooser chooser = new JFileChooser(System.getProperty("user.home") + "/Desktop");
        chooser.setSelectedFile(name);
        int select = chooser.showSaveDialog(chooser);
        if (select == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                FileWriter fw = new FileWriter(file);
                Table tb= new Table();
                fw.write("Danh sách mức lương của nhân viên.\n\n\n");
                fw.write(line());
                
                //In tiêu đề
                fw.write(String.format("|%-10s", tb.getColumnName(0)));
                fw.write(String.format("|%-25s", tb.getColumnName(1)));
                fw.write(String.format("|%-15s", tb.getColumnName(2)));
                fw.write(String.format("|%-15s", tb.getColumnName(3)));
                fw.write(String.format("|%-15s", tb.getColumnName(4)));
                fw.write(String.format("|%-15s", tb.getColumnName(5)));
                fw.write(String.format("|%-15s", tb.getColumnName(6)));
                fw.write(String.format("|%-15s", tb.getColumnName(7)));
                fw.write(String.format("|%-15s|\n", tb.getColumnName(8)));
                fw.write(line());
                //In dữ liệu
                for(int i=0 ;i <listL.size() ;i++){
                    fw.write(String.format("|%-10s",i ));
                    fw.write(String.format("|%-25s", listL.get(i).getHotenNV()));
                    fw.write(String.format("|%-15s", listL.get(i).getNgaySinh()));
                    fw.write(String.format("|%-15s", ""));
                    fw.write(String.format("|%-15s", listL.get(i).getTrinhDo()));
                    fw.write(String.format("|%-15s", listL.get(i).getChucDanh()));
                    fw.write(String.format("|%-15s", ""+listL.get(i).getBac()));
                    fw.write(String.format("|%-15s", ""+listL.get(i).getHeSoLuong()));
                    fw.write(String.format("|%-15s|\n", listL.get(i).getThoiDiem()));
                }
                fw.write(line());
                fw.flush();
                fw.close();
                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
                e2.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String sql = "Select * from LUONG right join NHANVIEN on LUONG.MaNhanVien = NHANVIEN.MaNhanVien"
                + " where NHANVIEN.MaNhanVien not in (Select MaNhanVien from LUONG)";
        LinkedList<Luong> listNew = db.getALLData(sql);
        String manv = (String) JOptionPane.showInputDialog(this, "Nhập mã nhân viên:", "Thêm mới",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                "");

        //Thêm
        if (manv != null && !manv.isEmpty()) {
            int index = -1;
            for (Luong i : listNew) {
                if (i.getMaNV().trim().equalsIgnoreCase(manv.trim())) {
                    index = listNew.indexOf(i);
                    break;
                }
            }
            if (index != -1) {
                Edit them = new Edit(listNew.get(index), jTable1, listL, "new");
                them.setVisible(true);
                listNew.remove(index);
            } else {
                for (Luong i : listL) {
                    if (i.getMaNV().trim().equalsIgnoreCase(manv.trim())) {
                        index = listL.indexOf(i);
                        break;
                    }
                }
                if (index != -1) {
                    JOptionPane.showMessageDialog(null, "Bản ghi đã tồn tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Không tồn tại nhân viên " + manv, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectedRow = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        if (selectedRow == -1) {
            String manv = (String) JOptionPane.showInputDialog(this, "Nhập mã nhân viên:", "Xóa",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    null,
                    "");
            if (manv != null && !manv.isEmpty()) {
                for (Luong i : listL) {
                    if (i.getMaNV().trim().equalsIgnoreCase(manv.trim())) {
                        selectedRow = listL.indexOf(i);
                        break;
                    }
                }
                if (selectedRow != -1) {
                    int rs = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa lương nhân viên " + listL.get(selectedRow).getMaNV(), "Cẩn thận", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if (rs == 0) {
                        db.delete(listL.get(selectedRow));
                        listL.remove(selectedRow);
                        jTable1.setModel(new Table(listL));
                        selectedRow = -1;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Bản ghi không tồn tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
                
            }
        }else{
            int rs = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa lương nhân viên " + listL.get(selectedRow).getMaNV(), "Cẩn thận", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (rs == 0) {
                db.delete(listL.get(selectedRow));
                listL.remove(selectedRow);
                jTable1.setModel(new Table(listL));
                selectedRow = -1;
            }
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JPanel f = new JPanel(new GridLayout(2, 1));
        f.add(new Label("Sắp xếp theo :"));
        JComboBox<String>option = new JComboBox<String>(new String[]{"Họ tên","Bậc"});
        f.add(option);
        int result= JOptionPane.showConfirmDialog(null, f, "Sắp xếp",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(result == 0){
            switch(option.getSelectedIndex()){
                case 0 :
                    Comparator<Luong> c = (o1, o2) -> {
                        return o1.getHotenNV().compareToIgnoreCase(o2.getHotenNV()); //To change body of generated lambdas, choose Tools | Templates.
                    };
                    Collections.sort(listL, c);
                    break;
                case 1 :
                    Comparator<Luong> c1 = (o1, o2) -> {
                        return Integer.compare(o1.getBac(), o2.getBac()); //To change body of generated lambdas, choose Tools | Templates.
                    };
                    Collections.sort(listL, c1);
                    break;
            }
            jTable1.setModel(new Table(listL));
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        listL= db.getALLData("Select * from LUONG inner join NHANVIEN on LUONG.MaNhanVien = NHANVIEN.MaNhanVien");
        String sql = "Select * from LUONG right join NHANVIEN on LUONG.MaNhanVien = NHANVIEN.MaNhanVien"
                + " where NHANVIEN.MaNhanVien not in (Select MaNhanVien from LUONG)";
        LinkedList<Luong> listNew = db.getALLData(sql);
        jTable1.setModel(new Table(listL));
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình", "Questions", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (n == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLuongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLuongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLuongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLuongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLuongJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
